name: Ask LLM to Comment When 'chatcompletion' Label is Added

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for 'chatcompletion' label
        if: github.event.label.name == 'chatcompletion'
        run: |
          echo "Label 'chatcompletion' was added. Running the script."

          # Set required environment variables
          echo "GH_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

          # Run the script
          ./chatcompletion.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

