name: Ask LLM to Comment When 'chatcompletion' Label is Added

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for 'chatcompletion' label
        if: github.event.label.name == 'chatcompletion'
        run: |
          echo "Label 'chatcompletion' was added. Running the script."

          # Determine if the event is for an issue or pull request and set ISSUE_NUMBER
          if [ "${{ github.event.issue.number }}" != "" ]; then
            ISSUE_NUMBER=${{ github.event.issue.number }}
          elif [ "${{ github.event.pull_request.number }}" != "" ]; then
            ISSUE_NUMBER=${{ github.event.pull_request.number }}
          else
            echo "No issue or pull request number found."
            exit 1
          fi

          # Export environment variables
          export GH_PAT=${{ secrets.GH_PAT }}
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export ISSUE_NUMBER=$ISSUE_NUMBER

          # Run the script
          ./chatcompletion.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

